### ISSUE TITLE
[Agenda Item] Incubation forum

### ISSUE THREAD

**Issue by Sealjay** [Green-Software-Foundation/projects#37]
**Overview**:
> A suggestion for a monthly 15 minute call to discuss spinning up new projects, helping to unblock them, and share expertise.

**Related topic**: The type of agenda item you want to propose.
- [ ] Governance: New project
- [X] Governance: Other
- [X] Process
- [ ] External Engagement
- [ ] Technology
- [ ] Other

**Related working groups**:

- [ ] Community
- [ ] Open Source
- [ ] Policy
- [ ] Standards
- [X] Oversight Committee

**Related issues or discussions**:

Please list all related issues so that we can see the originating conversation, e.g. #10 or https://github.com/Green-Software-Foundation/discussions/discussions/5

**More information**:
> Any other information you want to add.

**Comment by seanmcilroy29** [comment]
This has been added as an agenda item to the monthly OC Chair sync

**Comment by jawache** [comment]
I just want to surface this again, love the idea and we should streamline and support the process for incubation projects to be launched.

Rather than another meeting how about we kick start the social calls we used to have. We ran them monthly one in Asia times and one in US times. Mostly for new members, we'd run them through how the GSF works, how to ask for things, how to get involved in WG's/Projects. How to launch projects. We'd sometimes have project leads come in and give talks (it was a channel to attract contributors to your project)

@NAMRATA-WOKE as the newly minted member relationship lead how does that sound?

**Comment by srini1978** [comment]
Love the idea of Hatch calls @Sophietn @tmcclell @rubydickinson19 

How do we invite participants to these calls ? Are these for anyone to attend ? 

I am wondering that since these are once in a quarter calls, can we have a fixed set of projects pre-determined for atleast part of the hatch call. This way we would still have an engaging session even if the hatch call has less attendance or the attendees have come into the call with no specific ask.

**Comment by Sophietn** [comment]
Thank you for your input @srini1978! 

We can make the call 1 hour. Aiming for mid March for the first one. 

I propose the call should be open to any volunteer from a GSF member organisation, as only this audience can raise / lead projects within the GSF. 
I propose we would invite participants through multiple routes:
- Hatch program set up like a usual project, so members can [subscribe](https://greensoftware.foundation/subscribe/) to automatically receive the event calendar invite and join a shared google group mailing list
- @NAMRATA-WOKE to include open invitation to the Hatch call in the closest gsf-all newsletter to the date
- @NAMRATA-WOKE to include open invitation to the Hatch call in the closest member org lead newsletter to the date
- @Sophietn to create a confluence page outlining the Hatch call, signposting volunteers to subscribe to receive invite
- @Sophietn to send reminder and how to prep email 1 week before the event, to the 'subscribed' participants on the hatch call mailing list 

I love the idea of having a set of pre-determined project ideas we could discuss, if no participants come with a specific ask or their own new idea to raise. Perhaps we could ask all the WG chairs for their suggested ideas?
